/* Generated By:JavaCC: Do not edit this line. VELParserConstants.java */
/* Insert the default contents of the file here.  May need imoprts etc.
 */
package velexplanation.vel.parsing;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface VELParserConstants {

    /**
     * End of File.
     */
    int EOF = 0;
    /**
     * RegularExpression Id.
     */
    int FOP = 5;
    /**
     * RegularExpression Id.
     */
    int GOP = 6;
    /**
     * RegularExpression Id.
     */
    int XOP = 7;
    /**
     * RegularExpression Id.
     */
    int NEG = 8;
    /**
     * RegularExpression Id.
     */
    int UOP = 9;
    /**
     * RegularExpression Id.
     */
    int VOP = 10;
    /**
     * RegularExpression Id.
     */
    int WOP = 11;
    /**
     * RegularExpression Id.
     */
    int AND = 12;
    /**
     * RegularExpression Id.
     */
    int DUR = 13;
    /**
     * RegularExpression Id.
     */
    int OR = 14;
    /**
     * RegularExpression Id.
     */
    int IMP = 15;
    /**
     * RegularExpression Id.
     */
    int LPAR = 16;
    /**
     * RegularExpression Id.
     */
    int RPAR = 17;
    /**
     * RegularExpression Id.
     */
    int LANG = 18;
    /**
     * RegularExpression Id.
     */
    int RANG = 19;
    /**
     * RegularExpression Id.
     */
    int COM = 20;
    /**
     * RegularExpression Id.
     */
    int SEMI = 21;
    /**
     * RegularExpression Id.
     */
    int COL = 22;
    /**
     * RegularExpression Id.
     */
    int UNIV = 23;
    /**
     * RegularExpression Id.
     */
    int EXIS = 24;
    /**
     * RegularExpression Id.
     */
    int TRUE = 25;
    /**
     * RegularExpression Id.
     */
    int FALSE = 26;
    /**
     * RegularExpression Id.
     */
    int ID = 27;
    /**
     * RegularExpression Id.
     */
    int NUM = 28;

    /**
     * Lexical state.
     */
    int DEFAULT = 0;

    /**
     * Literal token values.
     */
    String[] tokenImage = {
            "<EOF>",
            "\" \"",
            "\"\\r\"",
            "\"\\t\"",
            "\"\\n\"",
            "\"F\"",
            "\"G\"",
            "\"X\"",
            "\"!\"",
            "\"U\"",
            "\"V\"",
            "\"W\"",
            "\"&\"",
            "\"*\"",
            "\"|\"",
            "\"->\"",
            "\"(\"",
            "\")\"",
            "\"<\"",
            "\">\"",
            "\",\"",
            "\";\"",
            "\":\"",
            "\"A\"",
            "\"E\"",
            "<TRUE>",
            "<FALSE>",
            "<ID>",
            "<NUM>",
    };

}
